### ISSUE TITLE
Descrever o método de amostragem que está no artigo

### ISSUE THREAD

**Issue by jpmarques19** [jpmarques19/fungal-networks#20]
No artigo: _"Topology of tree-mycorrhizal fungus interaction networks in xeric and mesic
Douglas-fir forests"_, os autores partilham o dataset resultante de um laborioso processo de amostragem de micorrizas.

Interessa-nos fazer uma descrição sumária  deste trabalho experimental.

**Comment by jcasimiro** [comment]
Efetuado no ponto 1.2 do projeto em "overleaf".
