### ISSUE TITLE
O conceito de "Wood-Wide Web"

### ISSUE THREAD

**Issue by jpmarques19** [jpmarques19/fungal-networks#7]
- [ ] Em que contexto este termo foi usado a primeira vez?
- [ ] Encontrar 3-5 artigos (cientificos ou de opinião) sobre a "Wood-Wide Web"
- [ ] Escrever entre 100 a 500 palavras

**Comment by jcasimiro** [comment]
Vê este [artigo](https://www.creatingtomorrowsforests.co.uk/blog/the-wood-wide-web-why-fungi-are-essential-to-forests). Explica o que é a "Wood-Wide Web" e como funciona.

**Comment by RuiNobre** [comment]
Bom dia, ontem consegui compilar alguma informação sobre o tema e anexo um documento que produzi.

**Comment by RuiNobre** [comment]
[Conceito da Wood Wide Web.odt](https://github.com/jpmarques19/fungal-networks/files/10148321/Conceito.da.Wood.Wide.Web.odt)

**Comment by RuiNobre** [comment]
tem 592 palavras 😊

**Comment by jpmarques19** [comment]
Muito bom Rui!
